### PR TITLE
Add loader impl

### LINKED ISSUE #22: Create a screen-responsive loader component
**Please describe the motive behind this issue.**
- Need a loader to indicate the loading state.

**Describe the solution you'd like to propose**
- The loader must be screen responsive
- Must be customizable in terms of styles

**Describe alternatives you've considered**
- NA

**Additional context**
- For inspiration/reference https://www.sliderrevolution.com/resources/css-loaders/

### PR DESCRIPTION
**Pull request by selamanse**
# Add Loaderspinner impl

## Description

Adds a configurable loader component for the content sections

Fixes #22 

## Type of change

Please mark the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

by running `nom run start` and testing manually via browser.

tbd: virtual DOM tests if desired.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by selamanse** [comment]
Screenshot 2021-10-31 at 19 23 25

**Comment by selamanse** [comment]
https://user-images.githubusercontent.com/3129224/139596782-aa143b42-9a03-4805-b4f0-d7159a7f6ebf.mov

**Comment by selamanse** [comment]
@DemonDaddy22 can you please add the hacktoberfest-accepted label to this PR? I'd like to add some test coverage but I think will only be able to do so tomorrow.

**Comment by DemonDaddy22** [comment]
@selamanse Can we do it without importing any additional package? Don't want to increase the bundle size just for a loader.

**Comment by selamanse** [comment]
@DemonDaddy22 I am almost finished with test coverage for this component. I am happy to code another component which is independent in another Issue/PR.

Also I think the impact on the bundle is not really big. But I think it's reasonable?

Before: 288K    total
After: 332K    total

**Comment by DemonDaddy22** [comment]
@selamanse It's a 50K increase in size for just a loader. I understand if you have done the test coverage for your code, but creating a new PR with a custom component won't help as I won't be able to merge this. If it's possible you can make the changes in this file itself. Code coverage, instead, could be moved to a new PR. I can create a separate issue for that, and code coverage can be done for other components as well.

**Comment by selamanse** [comment]
ok no worries. I will just remove the lib and code a simplified spinner. the test coverage is no big deal, I will just adjust it.
I will need a bit more time tho.

**Comment by DemonDaddy22** [comment]
@selamanse That would be great!

**Comment by selamanse** [comment]
Screenshot 2021-11-01 at 22 11 20

**Comment by selamanse** [comment]
Screenshot 2021-11-01 at 22 11 20

**Comment by selamanse** [comment]
@DemonDaddy22 this is all css ...not touching the build size (still 288K when I built it locally). also added test coverage

**Review by DemonDaddy22 — APPROVED** [review]
Looks good, need a few minor code quality tweaks, will do those after merging this PR.

**Pull request merged**
