### PR TITLE
Updated the script to not produce sourcemap for production build

### PR DESCRIPTION
**Pull request by ankitgauri26**

### CODE REVIEW

**Comment by DemonDaddy22** [comment]
@ankitgauri26 Can you please use the PULL_REQUEST_TEMPLATE to update your PR. Also, take the latest pull of the master branch as I made changes to the workflows. Hopefully, that will prevent your PR checks from failing.

**Comment by ankitgauri26** [comment]
@DemonDaddy22 - Sure. I'll use that.
I am totally new and haven't done PULL_REQUEST_TEMPLATE. Can you help me how I can do that? I have checked the main branch and found the template but how can i update it and where i can update the information. Thanks in advance.

**Comment by DemonDaddy22** [comment]
Hey @ankitgauri26, I'll create a workflow for it, for now, can you just copy it and paste it in the PR description, you can edit it there then.

**Comment by DemonDaddy22** [comment]
@ankitgauri26 If you create a new PR now, you'll be able to see the template come up automatically in PR's description.

**Comment by ankitgauri26** [comment]
As Suggested, will raise PR again

**Pull request closed without merging**
